name: Action Python

on: [push]

jobs:
  run-python:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Get Python version
        run: python -V

      - name: Install dependencies
        run: pip install discord
      - name: Run Python
        run: python main.py