name: Action Python

on: [push]

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Get Python version
        run: python -V

      - name: Make activate script executable
        run: chmod +x ./venv/Scripts/activate

      - name: Convert line endings to Unix format
        run: dos2unix ./venv/Scripts/activate
        if: runner.os == 'Linux'
      
      
      - name: Activate Venv
        run: ./venv/Scripts/activate
      # - name: Install dependencies
      #   run: pip install -r requirements.txt
      - name: Run Python
        run: python main.py