name: Action Python

on: [push]

jobs:
  run-python:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: Get Python version
        run: python -V

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        env:
          PIP_CACHE_DIR: ~/.cache/pip

      - name: Install dependencies
        run: pip install discord
      - name: Run Python
        run: python main.py